name: Build and publish on PyPI

on:
  release:
    types: [published]
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out ${{ github.ref_name }}
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.6"
      - name: Build
        run: uv build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish_pypi:
    name: Publish on PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/fast-forward-indexes/
    permissions:
      id-token: write
    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
